name = "propertyagent-pro"
compatibility_date = "2024-01-01"

[env.production]
name = "propertyagent-pro"

# Pages configuration
pages_build_output_dir = "dist"

# For static site deployment
[build]
command = "npm run build"
publish = "dist"

# Environment variables for Cloudflare Pages
[vars]
NODE_ENV = "production"
NEXT_PUBLIC_N8N_URL = "https://n8n.opsmith.biz/webhook"
NEXT_PUBLIC_CLOUDFLARE_WORKER_URL = "https://propertyagent-pro-tracker.mingquan.workers.dev"
NEXT_PUBLIC_AGENT_ID = "sarah-lim-001"
